version: '3.6'

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami'

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  producer:
    build: .
    depends_on:
      - kafka
    volumes:
      - './producer.js:/app/producer.js'
    command: node producer.js

  consumer-1:
    build: .
    depends_on:
      - kafka
    volumes:
      - './consumer.js:/app/consumer.js'
    environment:
      GROUP_ID: consumer-1
      CLIENT_ID: consumer-1
    command: node consumer.js

  consumer-2:
    build: .
    depends_on:
      - kafka
    volumes:
      - './consumer.js:/app/consumer.js'
    environment:
      GROUP_ID: consumer-2
      CLIENT_ID: consumer-2
    command: node consumer.js

  consumer-3:
    build: .
    depends_on:
      - kafka
    volumes:
      - './consumer.js:/app/consumer.js'
    environment:
      GROUP_ID: consumer-3
      CLIENT_ID: consumer-3
    command: node consumer.js

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
